### ISSUE TITLE
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by dm272** [developerChavezHarris/open-bot#3]
There is no requirements.txt file, i've followed all the commands in the `readme.md` however, step 5 does not work: `pip install -r requirements.txt`, it returns `Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'.` @developerChavezHarris

**Comment by developerChavezHarris** [comment]
requirements.txt was missing from the main repo folder, step 5 should now work.
