### ISSUE TITLE
UPDATE requirements.txt

### ISSUE THREAD

**Issue by dm272** [developerChavezHarris/open-bot#5]
I noticed after installing requirements and  proceeded to spin up the Django service, the following modules were missing: 

- django-cors-headers==3.2.1
- djangorestframework==3.11.0

I had to update the requirement.txt to include them. Not sure if this is native to my system or not, but i figured i'd mention it. @developerChavezHarris

**Comment by developerChavezHarris** [comment]
Hi @dm272 Thanks alot for pointing this out, the latest push of the requirements.txt file now includes these.
